[workspace]
members = ["packages/*"]

[workspace.dependencies]
cosmwasm-std = {version = "1.1.9", features = ["stargate","staking"]}
cosmwasm-schema = "1.1.9"
schemars = "0.8.11"
serde = { version = "1.0.152", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.38" }

